/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author guido
 */
public class Ventana2 extends javax.swing.JDialog {

    /**
     * Creates new form Ventana2
     */
    
    int contProcesos;
    int contID = 0;
    Proceso nuevoProceso;
    ArrayList<Proceso> listaProcesos = new ArrayList<Proceso>();  
    public Ventana2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jComboBoxAlgMem.setVisible(true);
        jComboBoxAlgMem1.setVisible(false);
        jTextFieldQuantum.setVisible(false);
        Quantum.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargaProcesos = new javax.swing.JLabel();
        Cp = new javax.swing.JLabel();
        TCp = new javax.swing.JTextField();
        TArribo = new javax.swing.JLabel();
        TA = new javax.swing.JTextField();
        TamProc = new javax.swing.JLabel();
        TamProc1 = new javax.swing.JTextField();
        RCPU1 = new javax.swing.JLabel();
        CPU1 = new javax.swing.JTextField();
        RCPU2 = new javax.swing.JLabel();
        CPU2 = new javax.swing.JTextField();
        RCPU3 = new javax.swing.JLabel();
        CPU3 = new javax.swing.JTextField();
        REentrada = new javax.swing.JLabel();
        RSalida = new javax.swing.JLabel();
        RE = new javax.swing.JTextField();
        RS = new javax.swing.JTextField();
        jButtonAñadir = new javax.swing.JButton();
        BotonAñadir = new javax.swing.JButton();
        Salirv2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableV2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabelMemoria = new javax.swing.JLabel();
        TamMemoria = new javax.swing.JTextField();
        MemoriaTam = new javax.swing.JLabel();
        TipoParticion = new javax.swing.JLabel();
        jComboBoxTipoParticion = new javax.swing.JComboBox<>();
        AlgMem = new javax.swing.JLabel();
        jComboBoxAlgMem = new javax.swing.JComboBox<>();
        jComboBoxAlgMem1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PP = new javax.swing.JLabel();
        AlgPla = new javax.swing.JLabel();
        jComboBoxAlgPla = new javax.swing.JComboBox<>();
        Quantum = new javax.swing.JLabel();
        jTextFieldQuantum = new javax.swing.JTextField();
        FondoV2 = new javax.swing.JLabel();
        jButtonAñadir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        CargaProcesos.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        CargaProcesos.setForeground(new java.awt.Color(204, 0, 0));
        CargaProcesos.setText("CARGA DE PROCESOS");

        Cp.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        Cp.setForeground(new java.awt.Color(255, 255, 255));
        Cp.setText("Cantidad de Procesos");

        TCp.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        TCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCpActionPerformed(evt);
            }
        });

        TArribo.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        TArribo.setForeground(new java.awt.Color(255, 255, 255));
        TArribo.setText("Tiempo de Arribo");

        TA.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        TA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAActionPerformed(evt);
            }
        });

        TamProc.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        TamProc.setForeground(new java.awt.Color(255, 255, 255));
        TamProc.setText("Tamaño del proceso");

        TamProc1.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        TamProc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamProc1ActionPerformed(evt);
            }
        });

        RCPU1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        RCPU1.setForeground(new java.awt.Color(255, 255, 255));
        RCPU1.setText("Rafaga de CPU 1");

        CPU1.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        CPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPU1ActionPerformed(evt);
            }
        });

        RCPU2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        RCPU2.setForeground(new java.awt.Color(255, 255, 255));
        RCPU2.setText("Rafaga de CPU 2");

        CPU2.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        CPU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPU2ActionPerformed(evt);
            }
        });

        RCPU3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        RCPU3.setForeground(new java.awt.Color(255, 255, 255));
        RCPU3.setText("Rafaga de CPU 3");

        CPU3.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        CPU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPU3ActionPerformed(evt);
            }
        });

        REentrada.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        REentrada.setForeground(new java.awt.Color(255, 255, 255));
        REentrada.setText("Rafaga de Entrada");

        RSalida.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        RSalida.setForeground(new java.awt.Color(255, 255, 255));
        RSalida.setText("Rafaga de Salida");

        RE.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        RE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REActionPerformed(evt);
            }
        });

        RS.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        RS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSActionPerformed(evt);
            }
        });

        jButtonAñadir.setBackground(new java.awt.Color(0, 0, 102));
        jButtonAñadir.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonAñadir.setForeground(new java.awt.Color(0, 204, 204));
        jButtonAñadir.setText("AÑADIR");
        jButtonAñadir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        BotonAñadir.setText("Agregar");
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(CargaProcesos)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TArribo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Cp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TCp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(TamProc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TamProc1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RCPU2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RCPU3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CPU3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(REentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RE, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonAñadir)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(CargaProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonAñadir)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TamProc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TamProc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TArribo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RCPU2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RCPU3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPU3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 390));

        Salirv2.setBackground(new java.awt.Color(0, 51, 153));
        Salirv2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        Salirv2.setForeground(new java.awt.Color(0, 204, 204));
        Salirv2.setText("Salir");
        Salirv2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        Salirv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salirv2ActionPerformed(evt);
            }
        });
        getContentPane().add(Salirv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 60, 30));

        jTableV2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tamaño", "T Arribo", "CPU 1", "Entrada", "CPU2", "Salida", "CPU3"
            }
        ));
        jScrollPane1.setViewportView(jTableV2);
        if (jTableV2.getColumnModel().getColumnCount() > 0) {
            jTableV2.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 660, 190));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabelMemoria.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabelMemoria.setForeground(new java.awt.Color(153, 0, 0));
        jLabelMemoria.setText("MEMORIA");

        MemoriaTam.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        MemoriaTam.setForeground(new java.awt.Color(255, 255, 255));
        MemoriaTam.setText("Tamaño de memoria");

        TipoParticion.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        TipoParticion.setForeground(new java.awt.Color(255, 255, 255));
        TipoParticion.setText("Tipo de particiones");

        jComboBoxTipoParticion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fija", "Variable" }));
        jComboBoxTipoParticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoParticionActionPerformed(evt);
            }
        });

        AlgMem.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        AlgMem.setForeground(new java.awt.Color(255, 255, 255));
        AlgMem.setText("Algoritmo de asignacion");

        jComboBoxAlgMem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FirstFit", "BestFit" }));

        jComboBoxAlgMem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FirstFit", "WorstFit" }));
        jComboBoxAlgMem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlgMem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AlgMem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MemoriaTam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TipoParticion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAlgMem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TamMemoria)
                                .addComponent(jComboBoxTipoParticion, 0, 258, Short.MAX_VALUE)
                                .addComponent(jComboBoxAlgMem1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TamMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemoriaTam, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoParticion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoParticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlgMem)
                    .addComponent(jComboBoxAlgMem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAlgMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 390, 150));

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EJECUTAR Y GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 660, 230, 30));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("EJECUTAR");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 663, 180, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        PP.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        PP.setForeground(new java.awt.Color(153, 0, 0));
        PP.setText("PLANIFICACION DE PROCESOS");

        AlgPla.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        AlgPla.setForeground(new java.awt.Color(255, 255, 255));
        AlgPla.setText("Algoritmo de planificacion de procesos");

        jComboBoxAlgPla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SJF", "SRTF", "ROUND ROBIN" }));
        jComboBoxAlgPla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlgPlaActionPerformed(evt);
            }
        });

        Quantum.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Quantum.setForeground(new java.awt.Color(255, 255, 255));
        Quantum.setText("Quantum");

        jTextFieldQuantum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PP, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlgPla, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAlgPla, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quantum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlgPla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAlgPla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quantum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 360, 180));

        FondoV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo-de-pantalla-Sistemas-Operativos-16.jpg"))); // NOI18N
        FondoV2.setText("dsad");
        getContentPane().add(FondoV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 710));

        jButtonAñadir1.setBackground(new java.awt.Color(0, 0, 102));
        jButtonAñadir1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonAñadir1.setForeground(new java.awt.Color(0, 204, 204));
        jButtonAñadir1.setText("AÑADIR");
        jButtonAñadir1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        jButtonAñadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadir1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAñadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Salirv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salirv2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Salirv2ActionPerformed

    private void TCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCpActionPerformed

    private void TAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAActionPerformed

    private void TamProc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamProc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TamProc1ActionPerformed

    private void CPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPU1ActionPerformed

    private void CPU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPU2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPU2ActionPerformed

    private void CPU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPU3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPU3ActionPerformed

    private void REActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REActionPerformed

    private void RSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSActionPerformed

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
        // TODO add your handling code here:
        if (TCp.getText().equals("")||(TCp.getText().equals("0"))){
            JOptionPane.showMessageDialog(rootPane, "Debe definir la cantidad de procesos");
        } else {
            contProcesos = Integer.parseInt(TCp.getText());
            TCp.setEnabled(false);
            }
        
        
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        // TODO add your handling code here:
        if (contProcesos > 0) {
            contProcesos = contProcesos - 1;
            if(TamProc1.getText().equals("")||(TA.getText().equals(""))||(CPU1.getText().equals(""))||(CPU2.getText().equals(""))||(CPU3.getText().equals(""))||(RE.getText().equals(""))||(RS.getText().equals(""))){
                JOptionPane.showMessageDialog(rootPane, "No completo todos los espacios");
            }
            if(TamProc1.getText().equals("0")||(CPU1.getText().equals("0"))||(CPU2.getText().equals("0"))||(CPU3.getText().equals("0"))||(RE.getText().equals("0"))||(RS.getText().equals("0"))){
                JOptionPane.showMessageDialog(rootPane, "Unicamente el Tiempo de Arribo puede ser 0");
            }
            contID = contID + 1;
            nuevoProceso = new Proceso(contID,Integer.parseInt(TA.getText()), Integer.parseInt(TamProc1.getText()), Integer.parseInt(CPU1.getText()), Integer.parseInt(CPU2.getText()), Integer.parseInt(CPU3.getText()), Integer.parseInt(RE.getText()), Integer.parseInt(RS.getText()));
            listaProcesos.add(nuevoProceso);
            GenerarTabla();
        } else { JOptionPane.showMessageDialog(rootPane, "No se pueden añadir mas procesos");
        }
        
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jComboBoxTipoParticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoParticionActionPerformed
        // TODO add your handling code here:
        if (jComboBoxTipoParticion.getSelectedIndex() == 1) {
            jComboBoxAlgMem.setVisible(false);
            jComboBoxAlgMem1.setVisible(true);
           
        } else {
            jComboBoxAlgMem.setVisible(true);
            jComboBoxAlgMem1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxTipoParticionActionPerformed

    private void jTextFieldQuantumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantumActionPerformed

    private void jComboBoxAlgMem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlgMem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlgMem1ActionPerformed

    private void jComboBoxAlgPlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlgPlaActionPerformed
        if (jComboBoxAlgPla.getSelectedIndex() == 3) {
            jTextFieldQuantum.setVisible(true);
            Quantum.setVisible(true);
           
        } else{
            jTextFieldQuantum.setVisible(false);
            Quantum.setVisible(false);
        
            }
    }//GEN-LAST:event_jComboBoxAlgPlaActionPerformed

    private void jButtonAñadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadir1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void GenerarTabla() {     
        String data [][] = new String [listaProcesos.size()][8];
        for (int i = 0; i < listaProcesos.size(); i++) {
                data[i][0] = Integer.toString(listaProcesos.get(i).getID());
                data[i][1] = Integer.toString(listaProcesos.get(i).getTamaño());
                data[i][2] = Integer.toString(listaProcesos.get(i).getTA());
                data[i][3] = Integer.toString(listaProcesos.get(i).getCPU1());
                data[i][4] = Integer.toString(listaProcesos.get(i).getEntrada());
                data[i][5] = Integer.toString(listaProcesos.get(i).getCPU2());
                data[i][6] = Integer.toString(listaProcesos.get(i).getSalida());
                data[i][7] = Integer.toString(listaProcesos.get(i).getCPU3());
        }
        jTableV2.setModel(new javax.swing.table.DefaultTableModel(
            data, new String [] {"ID", "Tamaño", "T Arribo", "CPU 1", "Entrada", "CPU 2","Salida", "CPU 3"}
        ));
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana2 dialog = new Ventana2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlgMem;
    private javax.swing.JLabel AlgPla;
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JTextField CPU1;
    private javax.swing.JTextField CPU2;
    private javax.swing.JTextField CPU3;
    private javax.swing.JLabel CargaProcesos;
    private javax.swing.JLabel Cp;
    private javax.swing.JLabel FondoV2;
    private javax.swing.JLabel MemoriaTam;
    private javax.swing.JLabel PP;
    private javax.swing.JLabel Quantum;
    private javax.swing.JLabel RCPU1;
    private javax.swing.JLabel RCPU2;
    private javax.swing.JLabel RCPU3;
    private javax.swing.JTextField RE;
    private javax.swing.JLabel REentrada;
    private javax.swing.JTextField RS;
    private javax.swing.JLabel RSalida;
    private javax.swing.JButton Salirv2;
    private javax.swing.JTextField TA;
    private javax.swing.JLabel TArribo;
    private javax.swing.JTextField TCp;
    private javax.swing.JTextField TamMemoria;
    private javax.swing.JLabel TamProc;
    private javax.swing.JTextField TamProc1;
    private javax.swing.JLabel TipoParticion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonAñadir1;
    private javax.swing.JComboBox<String> jComboBoxAlgMem;
    private javax.swing.JComboBox<String> jComboBoxAlgMem1;
    private javax.swing.JComboBox<String> jComboBoxAlgPla;
    private javax.swing.JComboBox<String> jComboBoxTipoParticion;
    private javax.swing.JLabel jLabelMemoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableV2;
    private javax.swing.JTextField jTextFieldQuantum;
    // End of variables declaration//GEN-END:variables
}
